### ISSUE TITLE
i18n support?

### ISSUE THREAD

**Issue by CaiMiao** [D4koon/MedianStats#1]
I can help with Chinese language, as I'm also the author of the MXL community Chinese language patch.

**Comment by D4koon** [comment]
Hello
good to hear that you want to contribute.
I now implemented the code for i18n and pushed it on development.
Could you make the translataion in the following file?
https://github.com/D4koon/MedianStats/blob/development/MedianStats/resources/translations/StringResources.zh.xaml

Im not sure which is the correct local i used simply zh for now but if that is wrong correct it yourself in the pullrequest or tell me

Thanks and best regards

**Comment by CaiMiao** [comment]
there's some need to also translate in-box stats strings, any plan?

**Comment by D4koon** [comment]
Yes, i forgot about those.

**Comment by D4koon** [comment]
Finaly i also added the strings for the stat-values.
Was alot more work then i thought :sweat_smile:
Pushed to ff1b07fe16be1dbd78b5ecbe780982ecd6974d33

Happy translating and thanks again

Edit: I forgot to copy the new strings over to StringResources.zh.xaml from StringResources.xaml
So just copy them over...

**Comment by CaiMiao** [comment]
![image](https://user-images.githubusercontent.com/4640483/91334152-801dae80-e809-11ea-8a59-22a80b917bf9.png)
Right click menu not get strings

![image](https://user-images.githubusercontent.com/4640483/91334331-c2df8680-e809-11ea-973b-0fb013da6352.png)

Mouse double click on Intellisence result still get the former inputed string remained (I typed `FLY` and `FLY` still remains)
